### ISSUE TITLE
Horizontally scrollable tabset

### ISSUE THREAD

**Issue by szh** [valor-software/ngx-bootstrap#1527]
I'm using ng2-bootstrap tabs in a mobile web site, but on small screens there are too many tabs to fit on the screen. I am able to get the tabs to scroll like this:

```html
<tabset class="tabset-scrollable">
```
```less
.tabset-scrollable .nav-tabs {
  display: -webkit-box;
  display: -webkit-flex;
  display: flex;
  -webkit-flex-wrap: nowrap;
  flex-wrap: nowrap;
  overflow-x: auto;
  overflow-y: hidden;
  -webkit-overflow-scrolling: touch;

  & > li {
    float: none;
    -webkit-flex: 0 0 auto;
    flex: 0 0 auto;
  }
}
```

However, the user has no indication that they're scrollable. I'd like to show a scroll shadow, something like http://codepen.io/matthewbeta/pen/fzoHI
The issue is that this requires CSS styling on a parent element, but the tabs `<ul>` parent also contains the tab content, which isn't scrollable.
![capture](https://cloud.githubusercontent.com/assets/546965/22126417/944f9d48-de65-11e6-8cf5-aeb273c47808.PNG)

Is there any way to achieve this effect? Thank you.
