### ISSUE TITLE
ProgressBar "active" not working

### ISSUE THREAD

**Issue by szh** [valor-software/ngx-bootstrap#1994]
The [docs](http://valor-software.com/ngx-bootstrap/#/progressbar) state that adding the classes "progress-striped active" to a `<progressbar>` will activate the animation. However, this doesn't appear to be working, even on the docs (I'm using Chrome 58 on Windows). It seems that the "active" class needs to be added to the div that's created inside of the component, like this:
```
<div progress max="100" class="progress active">
      ...
</div>
```

**Comment by szh** [comment]
I created a workaround. Add the following CSS:
```css
.progress-striped.active .progress-bar {
  -webkit-animation: progress-bar-stripes 2s linear infinite;
  animation: progress-bar-stripes 2s linear infinite;
}
```
