### ISSUE TITLE
Change icon for timepicker

### ISSUE THREAD

**Issue by TolotraRam** [valor-software/ngx-bootstrap#2274]
Hi,
Is there a way to change icon for timepicker and datepicker use like fontawesome for example ?

**Comment by 7185** [comment]
You can redefine the `glyphicon` CSS classes with the content of the `fa` classes.
This is a common thing among bs4 users.
Basically you put this in your global styles.css:
```css
.glyphicon {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome;
  font-size: inherit;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.glyphicon-chevron-left:before {
  content: "\f053";
}

.glyphicon-chevron-right:before {
  content: "\f054";
}

.glyphicon-chevron-up:before {
  content: "\f077";
}

.glyphicon-chevron-down:before {
  content: "\f078";
}
```
or even better if you use styles.scss:
```sass
.glyphicon {
  @extend .fa;

  &.glyphicon-chevron-left {
    @extend .fa-chevron-left;
  }

  &.glyphicon-chevron-right {
    @extend .fa-chevron-right;
  }

  &.glyphicon-chevron-up {
    @extend .fa-chevron-up;
  }

  &.glyphicon-chevron-down {
    @extend .fa-chevron-down;
  }
}
```
