### ISSUE TITLE
Set Tooltip Width and wrap the text

### ISSUE THREAD

**Issue by mshirishkumar** [valor-software/ngx-bootstrap#808]
Hi
Could you please let me know how can we set tooltip width and also wrap the text in single line.

**Comment by brandonreid** [comment]
@mshirishkumar If you inspect, you'll see the tooltip is placed after the item it's referencing, by default. So you can target it with CSS for widths and stuff.

Example...

HTML

``` html
<div class="some-container">
  <button tooltip="My button tooltip with lots and lots of text.">Hover Me</button>
</div>
```

CSS

``` css
.some-container .tooltip .tooltip-inner {
  width: 7em;
  white-space: normal;
}
```
